//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDFEntity", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class EDFEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication1.ServiceReference1.SharePointEntity[] EDFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication1.ServiceReference1.SharePointEntity[] EDF {
            get {
                return this.EDFField;
            }
            set {
                if ((object.ReferenceEquals(this.EDFField, value) != true)) {
                    this.EDFField = value;
                    this.RaisePropertyChanged("EDF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SharePointEntity", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class SharePointEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication1.ServiceReference1.WebApplicationEntity[] SharePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication1.ServiceReference1.WebApplicationEntity[] SharePoint {
            get {
                return this.SharePointField;
            }
            set {
                if ((object.ReferenceEquals(this.SharePointField, value) != true)) {
                    this.SharePointField = value;
                    this.RaisePropertyChanged("SharePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebApplicationEntity", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class WebApplicationEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication1.ServiceReference1.SiteCollectionEntity[] WebApplicationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication1.ServiceReference1.SiteCollectionEntity[] WebApplication {
            get {
                return this.WebApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.WebApplicationField, value) != true)) {
                    this.WebApplicationField = value;
                    this.RaisePropertyChanged("WebApplication");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteCollectionEntity", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class SiteCollectionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication1.ServiceReference1.SiteEntity[] SitesCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication1.ServiceReference1.SiteEntity[] SitesCollection {
            get {
                return this.SitesCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SitesCollectionField, value) != true)) {
                    this.SitesCollectionField = value;
                    this.RaisePropertyChanged("SitesCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteEntity", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class SiteEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CharteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionEspaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FermeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LangueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginProprietaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NiveauAudienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomEspaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomProprietaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OffreServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeAccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionModeleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Charte {
            get {
                return this.CharteField;
            }
            set {
                if ((object.ReferenceEquals(this.CharteField, value) != true)) {
                    this.CharteField = value;
                    this.RaisePropertyChanged("Charte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeUM {
            get {
                return this.CodeUMField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeUMField, value) != true)) {
                    this.CodeUMField = value;
                    this.RaisePropertyChanged("CodeUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionEspace {
            get {
                return this.DescriptionEspaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionEspaceField, value) != true)) {
                    this.DescriptionEspaceField = value;
                    this.RaisePropertyChanged("DescriptionEspace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionField, value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ferme {
            get {
                return this.FermeField;
            }
            set {
                if ((object.ReferenceEquals(this.FermeField, value) != true)) {
                    this.FermeField = value;
                    this.RaisePropertyChanged("Ferme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Langue {
            get {
                return this.LangueField;
            }
            set {
                if ((object.ReferenceEquals(this.LangueField, value) != true)) {
                    this.LangueField = value;
                    this.RaisePropertyChanged("Langue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginAdmin {
            get {
                return this.LoginAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginAdminField, value) != true)) {
                    this.LoginAdminField = value;
                    this.RaisePropertyChanged("LoginAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginProprietaire {
            get {
                return this.LoginProprietaireField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginProprietaireField, value) != true)) {
                    this.LoginProprietaireField = value;
                    this.RaisePropertyChanged("LoginProprietaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modele {
            get {
                return this.ModeleField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeleField, value) != true)) {
                    this.ModeleField = value;
                    this.RaisePropertyChanged("Modele");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NiveauAudience {
            get {
                return this.NiveauAudienceField;
            }
            set {
                if ((object.ReferenceEquals(this.NiveauAudienceField, value) != true)) {
                    this.NiveauAudienceField = value;
                    this.RaisePropertyChanged("NiveauAudience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomAdmin {
            get {
                return this.NomAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.NomAdminField, value) != true)) {
                    this.NomAdminField = value;
                    this.RaisePropertyChanged("NomAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomEspace {
            get {
                return this.NomEspaceField;
            }
            set {
                if ((object.ReferenceEquals(this.NomEspaceField, value) != true)) {
                    this.NomEspaceField = value;
                    this.RaisePropertyChanged("NomEspace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomProprietaire {
            get {
                return this.NomProprietaireField;
            }
            set {
                if ((object.ReferenceEquals(this.NomProprietaireField, value) != true)) {
                    this.NomProprietaireField = value;
                    this.RaisePropertyChanged("NomProprietaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OffreService {
            get {
                return this.OffreServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.OffreServiceField, value) != true)) {
                    this.OffreServiceField = value;
                    this.RaisePropertyChanged("OffreService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeAcces {
            get {
                return this.TypeAccesField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeAccesField, value) != true)) {
                    this.TypeAccesField = value;
                    this.RaisePropertyChanged("TypeAcces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionModele {
            get {
                return this.VersionModeleField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionModeleField, value) != true)) {
                    this.VersionModeleField = value;
                    this.RaisePropertyChanged("VersionModele");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        WpfApplication1.ServiceReference1.EDFEntity GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.EDFEntity> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WpfApplication1.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WpfApplication1.ServiceReference1.IService>, WpfApplication1.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfApplication1.ServiceReference1.EDFEntity GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.EDFEntity> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
